spring:
  application:
    name: spring-security-basic-jwt



  datasource:
    url: jdbc:postgresql://localhost:5432/telusko-sec
    password: postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true





