
spring:
  application:
    name: spring-security-basic-jwt

  security:
    user:
      name: user
      password: pass

  datasource:
    url: jdbc:postgresql://localhost:5432/telusko-sec
    password: postgres
    username: postgres

#  jpa:
#    hibernate:
#      ddl-auto: update